
#define BATCH_SIZE 64
#define HIDDEN_DIM 8192   
#define CLUSTER_SIZE 2 // 2 4 8 16
#define DIM_PER_BLOCK (HIDDEN_DIM / CLUSTER_SIZE)
#define NUM_PER_THREAD 8
#define BLOCK_SIZE (DIM_PER_BLOCK / NUM_PER_THREAD)
#define WARP_SIZE 32
#define NUM_WARPS (BLOCK_SIZE / WARP_SIZE)
